[phases.setup]
nixPkgs = ['python311Full', 'python311Packages.pip', 'python311Packages.virtualenv']

[phases.install]
cmds = [
  'python -m venv /app/venv',
  '/app/venv/bin/pip install --upgrade pip',
  '/app/venv/bin/pip install -r requirements.txt'
]

[start]
cmd = '/app/venv/bin/gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 600 --worker-class gthread --max-requests 100 --max-requests-jitter 10 wsgi:application'
